config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :video_selectors
  resources :audio_selectors
  resources :input_types
  resources :input_processings do
    collection do
      get :change_attributes_wid
      get :change_attributes_wlabel

      get :prepare_wid
      get :prepare_wlabel
      get :prepare

      get :activate_wid
      get :activate_wlabel
      get :activate
      
      get :delete_wid
      get :delete_wlabel
      get :delete

      get :add_wids
      get :add
      
      get :replace_wids
      get :replace
      
      get :single_add_wids
      get :single_add
      
      post :reorder
    end
  end
  
  resources :live_events do
    collection do 
      get :start
      get :stop
      get :cancel
      get :archive
      get :reset
      get :priority
      get :set_priority
    end
  end
  
  
  root to: "live_events#index"

end

app/models/input.rb
class Input < ActiveRecord::Base

    has_one :audio_selector
    accepts_nested_attributes_for :audio_selector, allow_destroy: true
    
    has_one :video_selector
    accepts_nested_attributes_for :video_selector, allow_destroy: true
    
    belongs_to :live_event
    
end

app/models/input_type.rb
class InputType < ActiveRecord::Base
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]

  # GET /inputs
  # GET /inputs.json
  def index
    
    @selected = -1

    @inputs = [] 
    
    if params[:live_event].present? then 
      if params[:live_event][:event_id].present? then
        @selected = params[:live_event][:event_id]
        @inputs = Input.where(live_event_id: params[:live_event][:event_id] )
      end
    end
    if params[:live_event_id].present? then
      @inputs = Input.where(live_event_id: params[:live_event_id] )
    end

  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    if params[:live_event_id].present? then
      @live_event_id = params[:live_event_id]
    end

    @input = Input.new
    @input.build_audio_selector
    @input.build_video_selector
  end

  # GET /inputs/1/edit
  def edit
    if params[:live_event_id].present? then
      @live_event_id = params[:live_event_id]
    end

  end

  # POST /inputs
  # POST /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: 'Input was successfully updated.' }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url, notice: 'Input was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.require(:input).permit(:live_event_id, :input_label, :loop_source, :input_type, :quad, :uri, audio_selector_attributes: [ :audio_id, :id, :default_selection, :track ], video_selector_attributes: [  :video_id, :id, :default_selection, :track ])
    end
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/_form.html.erb
<%= form_for(@input) do |f| %>
  <% if @input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% @input.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :live_event_id %><br>
    <%= f.text_field :live_event_id, value: @live_event_id %>
  </div>
  <div class="field">
    <%= f.label :input_label %><br>
    <%= f.text_field :input_label %>
  </div>
  <div class="field">
    <%= f.label :loop_source %><br>
    <%= f.check_box :loop_source %>
  </div>
  <div class="field">
    <%= f.label :input_type %><br>
    <%= f.collection_select :input_type, InputType.all, :id, :type_name, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :quad %><br>
    <%= f.check_box :quad %>
  </div>
  <div class="field">
    <%= f.label :uri %><br>
    <%= f.text_field :uri %>
  </div>

  <strong> Audio Selector </strong></br></br>
  <%= f.fields_for :audio_selector do |ff| %>

    <div class="field">
      <%= ff.label :audio_id %><br>
      <%= ff.text_field :audio_id %>
    </div>

    <div class="field">
      <%= ff.label :default_selection %>
      <%= ff.check_box :default_selection %>
    </div>
    <div class="field">
      <%= ff.label :track %><br>
      <%= ff.text_field :track %>
    </div>
  <% end %>

  <strong> Video Selector </strong></br></br>  
  <%= f.fields_for :video_selector do |ff| %>

    <div class="field">
      <%= ff.label :video_id %><br>
      <%= ff.text_field :video_id %>
    </div>

    <div class="field">
      <%= ff.label :default_selection %>
      <%= ff.check_box :default_selection %>
    </div>
    <div class="field">
      <%= ff.label :track %><br>
      <%= ff.text_field :track %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inputs/edit.html.erb
<div class="container">
    
<center><strong>Editing Input</strong></center>

<%= render 'form' %>

<%= link_to 'Show', @input, class: 'btn-sm btn-default' %> |
<%= link_to 'Back', inputs_path, class: 'btn-sm btn-default' %>

</div>

app/views/inputs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<center><strong>Listing Inputs</strong></center>

<%= form_tag inputs_path, :method => "get" do %>
  <% if @selected.to_i == -1 then %>
    <%= collection_select(:live_event, :event_id, LiveEvent.all, :event_id, :name, :prompt => true   ) %>
  <% else %>
    <%= collection_select(:live_event, :event_id, LiveEvent.all, :event_id, :name, :prompt => true, :selected => @selected   ) %>
  <% end %>  

  <%= submit_tag "Filter inputs" %>
<% end %>
<br/>
<br/>

<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        Live event
      </th>
      <th>
        Input label
      </th>
      <th>
        Loop source
      </th>
      <th>
        Quad
      </th>
      <th>
        Input type
      </th>
      <th>
        Uri
      </th>
      <th>
        Audio
      </th>
      <th>
        Video
      </th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    
    <% @inputs.each do |input| %>
      <tr>
        <td><%= link_to input.live_event.name, live_event_path(input.live_event), class: 'btn-sm btn-default' %></td>
        <td><%= input.input_label %></td>
        <td><%= input.loop_source %></td>
        <td><%= input.input_type %></td>
        <td><%= input.quad %></td>
        <td><%= input.uri %></td>
        <td><%= link_to input.audio_selector.id, audio_selector_path(input.audio_selector), class: 'btn-sm btn-default' %></td>
        <td><%= link_to input.video_selector.id, video_selector_path(input.video_selector) , class: 'btn-sm btn-default' %></td>
        <td><input type="checkbox" id="<%= input.id %>" class="live_event_input" name="post[added] value="1" /> <%= link_to 'Add', single_add_wids_input_processings_path(id: input.id, event_id: input.live_event ), remote: true, class: 'btn-sm btn-default', data: {'input-id': input.id}  %> </td>
        <td><%= link_to 'Show', input, class: 'btn-sm btn-default' %></td>
        <td><%= link_to 'Edit', edit_input_path(input), class: 'btn-sm btn-default' %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path, class: 'btn-sm btn-success' %>

<button id="AddInputs" >Add inputs</button>

<button id="ReplacePlaylist" >Replace Playlist</button>

</div>

<div id="modal-window-prepare" class="modal fade"></div>
<div id="modal-window-activate" class="modal fade"></div>
<div id="modal-window-delete" class="modal fade"></div>
<div id="modal-window-single-add" class="modal fade"></div>
<div id="modal-window-change-attributes" class="modal fade"></div>

app/views/inputs/new.html.erb
<div class="container">
    
<center></strong>Create New Input</strong></center>

<%= render 'form' %>

<%= link_to 'Back', inputs_path, class: 'btn-sm btn-default' %>

</div>

app/views/inputs/show.html.erb
<div class="container">
  
<p id="notice"><%= notice %></p>

<p>
  <strong>Live event:</strong>
  <%= @input.live_event_id %>
</p>

<p>
  <strong>Input label:</strong>
  <%= @input.input_label %>
</p>

<p>
  <strong>Loop source:</strong>
  <%= @input.loop_source %>
</p>

<p>
  <strong>Input type:</strong>
  <%= @input.input_type %>
</p>

<p>
  <strong>Quad:</strong>
  <%= @input.quad %>
</p>

<p>
  <strong>Uri:</strong>
  <%= @input.uri %>
</p>

<p>
  <strong>Audio Selector id:</strong>
  <%= @input.audio_selector.audio_id %>
</p>

<p>
  <strong>Audio Selector default selection:</strong>
  <%= @input.audio_selector.default_selection %>
</p>

<p>
  <strong>Audio Selector track:</strong>
  <%= @input.audio_selector.track %>
</p>

<p>
  <strong>Video Selector id:</strong>
  <%= @input.video_selector.video_id %>
</p>

<p>
  <strong>Video Selector default selection:</strong>
  <%= @input.video_selector.default_selection %>
</p>

<p>
  <strong>Video Selector track:</strong>
  <%= @input.video_selector.track %>
</p>

<%= link_to 'Edit', edit_input_path(@input), class: 'btn-sm btn-default' %> |
<%= link_to 'Back', inputs_path, class: 'btn-sm btn-default' %>

</div>