config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :video_selectors
  resources :audio_selectors
  resources :input_types
  resources :input_processings do
    collection do
      get :change_attributes_wid
      get :change_attributes_wlabel

      get :prepare_wid
      get :prepare_wlabel
      get :prepare

      get :activate_wid
      get :activate_wlabel
      get :activate
      
      get :delete_wid
      get :delete_wlabel
      get :delete

      get :add_wids
      get :add
      
      get :replace_wids
      get :replace
      
      get :single_add_wids
      get :single_add
      
      post :reorder
    end
  end
  
  resources :live_events do
    collection do 
      get :start
      get :stop
      get :cancel
      get :archive
      get :reset
      get :priority
      get :set_priority
    end
  end
  
  
  root to: "live_events#index"

end

app/models/audio_selector.rb
class AudioSelector < ActiveRecord::Base
        belongs_to :input
end

app/controllers/audio_selectors_controller.rb
class AudioSelectorsController < ApplicationController
  before_action :set_audio_selector, only: [:show, :edit, :update, :destroy]

  # GET /audio_selectors
  # GET /audio_selectors.json
  def index
    @audio_selectors = AudioSelector.all
  end

  # GET /audio_selectors/1
  # GET /audio_selectors/1.json
  def show
  end

  # GET /audio_selectors/new
  def new
    @audio_selector = AudioSelector.new
  end

  # GET /audio_selectors/1/edit
  def edit
  end

  # POST /audio_selectors
  # POST /audio_selectors.json
  def create
    @audio_selector = AudioSelector.new(audio_selector_params)

    respond_to do |format|
      if @audio_selector.save
        format.html { redirect_to @audio_selector, notice: 'Audio selector was successfully created.' }
        format.json { render :show, status: :created, location: @audio_selector }
      else
        format.html { render :new }
        format.json { render json: @audio_selector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audio_selectors/1
  # PATCH/PUT /audio_selectors/1.json
  def update
    respond_to do |format|
      if @audio_selector.update(audio_selector_params)
        format.html { redirect_to @audio_selector, notice: 'Audio selector was successfully updated.' }
        format.json { render :show, status: :ok, location: @audio_selector }
      else
        format.html { render :edit }
        format.json { render json: @audio_selector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audio_selectors/1
  # DELETE /audio_selectors/1.json
  def destroy
    @audio_selector.destroy
    respond_to do |format|
      format.html { redirect_to audio_selectors_url, notice: 'Audio selector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_audio_selector
      @audio_selector = AudioSelector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def audio_selector_params
      params.require(:audio_selector).permit(:default_selection, :track)
    end
end

app/helpers/audio_selectors_helper.rb
module AudioSelectorsHelper
end

app/views/audio_selectors/_form.html.erb
<%= form_for(@audio_selector) do |f| %>
  <% if @audio_selector.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@audio_selector.errors.count, "error") %> prohibited this audio_selector from being saved:</h2>

      <ul>
      <% @audio_selector.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :audio_id %><br>
    <%= f.number_field :audio_id %>
  </div>

  <div class="field">
    <%= f.label :default_selection %><br>
    <%= f.check_box :default_selection %>
  </div>
  <div class="field">
    <%= f.label :track %><br>
    <%= f.number_field :track %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/audio_selectors/edit.html.erb
<div class="container">
    
<center><strong>Editing Audio Selector</strong></center>

<%= render 'form' %>

<%= link_to 'Show', @audio_selector %> |
<%= link_to 'Back', audio_selectors_path %>

</div>

app/views/audio_selectors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  
<center><strong>Listing Audio Selectors</strong></center>

<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>Default selection</th>
      <th>Track</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>

    <% @audio_selectors.each do |audio_selector| %>
      <tr>
        <td><%= audio_selector.default_selection %></td>
        <td><%= audio_selector.track %></td>
        <td><%= link_to 'Show', audio_selector %></td>
        <td><%= link_to 'Edit', edit_audio_selector_path(audio_selector) %></td>
        <td><%= link_to 'Destroy', audio_selector, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Audio selector', new_audio_selector_path %>

</div>

app/views/audio_selectors/new.html.erb
<div class="container">
    
<center><strong>New Audio Selector</strong></center>

<%= render 'form' %>

<%= link_to 'Back', audio_selectors_path %>

</div>

app/views/audio_selectors/show.html.erb
<div class="container">
  
<p id="notice"><%= notice %></p>

<p>
  <strong>Audio Id:</strong>
  <%= @audio_selector.audio_id %>
</p>

<p>
  <strong>Default selection:</strong>
  <%= @audio_selector.default_selection %>
</p>

<p>
  <strong>Track:</strong>
  <%= @audio_selector.track %>
</p>

<%= link_to 'Edit', edit_audio_selector_path(@audio_selector) %> |
<%= link_to 'Back', audio_selectors_path %>

</div>