config/routes.rb
Rails.application.routes.draw do
  resources :inputs
  resources :video_selectors
  resources :audio_selectors
  resources :input_types
  resources :input_processings do
    collection do
      get :change_attributes_wid
      get :change_attributes_wlabel

      get :prepare_wid
      get :prepare_wlabel
      get :prepare

      get :activate_wid
      get :activate_wlabel
      get :activate
      
      get :delete_wid
      get :delete_wlabel
      get :delete

      get :add_wids
      get :add
      
      get :replace_wids
      get :replace
      
      get :single_add_wids
      get :single_add
      
      post :reorder
    end
  end
  
  resources :live_events do
    collection do 
      get :start
      get :stop
      get :cancel
      get :archive
      get :reset
      get :priority
      get :set_priority
    end
  end
  
  
  root to: "live_events#index"

end

app/models/live_event.rb
class LiveEvent < ActiveRecord::Base
end

app/controllers/live_events_controller.rb
class LiveEventsController < ApplicationController
  before_action :set_live_event, only: [:edit, :update, :destroy]

  require 'rest-client'
  require 'nokogiri'

  include AuthElemental
  
  # GET /live_events
  # GET /live_events.json
  def index
    @result = headers("/live_events")

    @xml_response = RestClient::Request.execute(
       :method => :get,
       :url => "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events",
       :headers => { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml"
                    }
    )
    
    @doc = Nokogiri::XML(@xml_response)
    
    @live_events = @doc.xpath("//live_event")

  end

  # GET /live_events/1
  # GET /live_events/1.json
  def show

    if params[:id].present? then
        @id = params[:id].gsub(/\/live_events\/(\d*)/, '\1')
    end

    @result = headers("/live_events/" + @id)

    @xml_response = RestClient::Request.execute(
       :method => :get,
       :url => "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id,
       :headers => { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml"
                    }
    )

    @doc = Nokogiri::XML(@xml_response)

    @live_event_name = @doc.xpath("live_event/name").text
    @live_event_event_id = @doc.xpath("live_event/id").text
    @input_elements = @doc.xpath("//input")

    @inputs = Input.where(live_event_id: @id )

  end

  # GET /live_events/new
  def new
    @live_event = LiveEvent.new
  end

  # GET /live_events/1/edit
  def edit
  end

  # POST /live_events
  # POST /live_events.json
  def create
    @live_event = LiveEvent.new(live_event_params)

    respond_to do |format|
      if @live_event.save
        format.html { redirect_to @live_event, notice: 'Live event was successfully created.' }
        format.json { render :show, status: :created, location: @live_event }
      else
        format.html { render :new }
        format.json { render json: @live_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /live_events/1
  # PATCH/PUT /live_events/1.json
  def update
    respond_to do |format|
      if @live_event.update(live_event_params)
        format.html { redirect_to @live_event, notice: 'Live event was successfully updated.' }
        format.json { render :show, status: :ok, location: @live_event }
      else
        format.html { render :edit }
        format.json { render json: @live_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /live_events/1
  # DELETE /live_events/1.json
  def destroy
    @live_event.destroy
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: 'Live event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def start
    if params[:event_detail].present? then
        @id = params[:event_detail].gsub(/\/live_events\/(\d*)/, '\1')
    end
    
    @result = headers("/live_events/" + @id  + "/start" )

    @payload = "<start>" + @id + "</start>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/start"
    
    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: @failure }
      format.json { head :no_content }
    end
  end

  def stop
    if params[:event_detail].present? then
        @id = params[:event_detail].gsub(/\/live_events\/(\d*)/, '\1')
    end
    
    @result = headers("/live_events/" + @id  + "/stop" )

    @payload = "<stop>" + @id + "</stop>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/stop"

    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: @failure }
      format.json { head :no_content }
    end
  end

  def cancel
    if params[:event_detail].present? then
        @id = params[:event_detail].gsub(/\/live_events\/(\d*)/, '\1')
    end
    
    @result = headers("/live_events/" + @id  + "/cancel" )

    @payload = "<cancel>" + @id + "</cancel>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/cancel"

    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: @failure }
      format.json { head :no_content }
    end
  end
  
  def archive
    if params[:event_detail].present? then
        @id = params[:event_detail].gsub(/\/live_events\/(\d*)/, '\1')
    end
    
    @result = headers("/live_events/" + @id  + "/archive" )

    @payload = "<archive>" + @id + "</archive>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/archive"

    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: @failure }
      format.json { head :no_content }
    end
  end  
  
  def reset
    if params[:event_detail].present? then
        @id = params[:event_detail].gsub(/\/live_events\/(\d*)/, '\1')
    end
    
    @result = headers("/live_events/" + @id  + "/reset" )

    @payload = "<reset>" + @id + "</reset>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/reset"

    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|
      format.html { redirect_to live_events_url, notice: @failure }
      format.json { head :no_content }
    end
  end

  def priority
    if params[:priority].present? then
        @priority = params[:priority]
    end
    
    if params[:live_event_id].present? then
        @id = params[:live_event_id]
    end
  
    @result = headers("/live_events/" + @id  + "/priority" )

    @payload = "<priority>" + @priority + "</priority>"

    @url = "http://nqm7e3lvuev71.cloud.elementaltechnologies.com/live_events/" + @id + "/priority"

    RestClient::Request.new({
      method: :post,
      url: @url,
      payload: @payload,
      headers: { "X-Auth-User" => @result["X-Auth-User"],
                     "X-Auth-Expires" => @result['X-Auth-Expires'],
                     "X-Auth-Key" => @result['X-Auth-Key'],
                     "Accept" => "application/xml",
                     "Content-Type" =>  "application/xml" }
    }).execute do |response, request, result|
      case response.code
      when 422
        [ :error, response.to_str ]
      when 200
        [ :success, response.to_str ]
      else
        @failure =  response.to_str
      end
    end
    
    respond_to do |format|

app/helpers/live_events_helper.rb
module LiveEventsHelper
end

app/views/live_events/_form.html.erb
<%= form_for(@live_event) do |f| %>
  <% if @live_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@live_event.errors.count, "error") %> prohibited this live_event from being saved:</h2>

      <ul>
      <% @live_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br/>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit class: "btn-sm btn-primary"%>
  </div>
<% end %>

app/views/live_events/_set_priority.html.erb
    <%= render "layouts/set_priority_modal" %>

app/views/live_events/edit.html.erb
<div class="container">

<center><strong>Change Live Event Attributes Locally</strong></center>

<%= render 'form' %>

<%= link_to 'Show', @live_event, class: 'btn-sm btn-default' %> |
<%= link_to 'Back', live_events_path, class: 'btn-sm btn-default' %>

</div>

app/views/live_events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

<strong><center>Listing Live Events</center></strong>

<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        Event Name
      </th>
      <th>
        Event Id
      </th>
      <th colspan=6 ></th>
    </tr>
  </thead>
  <tbody>
    <% @live_events.each do |live_event| %>
        <tr  class="item">
        <td><%= link_to live_event.xpath("name").text + " Playlist", live_event_path(id: live_event.xpath('@href')) %></td>
        <td><%= live_event.xpath("@href").text.gsub(/\/live_events\/(\d*)/, '\1') %></td>
        
        <td><%= link_to 'Set Priority', set_priority_live_events_path(event_detail: live_event.xpath("@href").text), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' } %></td>
        <td><%= link_to 'Start', start_live_events_path(event_detail: live_event.xpath("@href").text), class: 'btn-sm btn-success', data: { confirm: 'Starting live event?' } %></td>
        <td><%= link_to 'Stop', stop_live_events_path(event_detail: live_event.xpath("@href").text), class: 'btn-sm btn-alert', data: { confirm: 'Stoping live event?' } %></td>
        <td><%= link_to 'Cancel', cancel_live_events_path(event_detail: live_event.xpath("@href").text), class: 'btn-sm btn-alert', data: { confirm: 'Canceling live event?' } %></td>
        <td><%= link_to 'Archive', archive_live_events_path(event_detail: live_event.xpath("@href").text), class: 'btn-sm btn-alert', data: { confirm: 'Archiving live event?' } %></td>
        <td><%= link_to 'Reset', reset_live_events_path(event_detail: live_event.xpath("@href").text), class: 'btn-sm btn-alert', data: { confirm: 'Reseting live event?' } %></td>
        <!--
        <td><%= link_to 'Edit', edit_live_event_path(live_event.xpath("id").text.to_i), class: 'btn-sm btn-default' %></td>
        <td><%= link_to 'Destroy', live_event_url(live_event.xpath("id").text.to_i), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-danger' %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Live event', new_live_event_path, class: 'btn-sm btn-default' %>

</div>

<div id="modal-window-set-priority" class="modal fade"></div>

app/views/live_events/new.html.erb
<div class="container">

<center><strong>New Live Event</strong></center>

<%= render 'form' %>

<%= link_to 'Back', live_events_path, class: 'btn-sm btn-default' %>

</div>

app/views/live_events/set_priority.js.erb
$("#modal-window-set-priority").html("<%= escape_javascript(render 'live_events/set_priority') %>")
$("#modal-window-set-priority").modal("show")

app/views/live_events/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">

<p>
  <strong>Event with name : <%= @live_event_name %> and id: <%= @live_event_event_id %></strong>
  <%= link_to 'Edit', edit_live_event_path(@live_event_event_id), class: 'btn-sm btn-default' %>  <%= link_to 'Back', live_events_path, class: 'btn-sm btn-default' %> 
</p>

<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        Order
      </th>
      <th>
        Active
      </th>
      <th>
        Uri
      </th>
      <th>
        Show XML
      </th>
      <th>
        Prepare
      </th>
      <th>
        Activate
      </th>
      <th>
        Delete
      </th>
    </tr>
  </thead>
  <tbody id="sortable-inputs" >
<% @input_elements.each  do |input|  %>

  <% if input.xpath('input_label').text.size > 0 then %> 
    <tr class="item" id="item_<%= input.xpath('order').text %>" >
    <td><%= input.xpath('order').text %></td><td><%= input.xpath('active').text %></td> <td><% if input.xpath('network_input/uri').text.length > 0 then %> <%= input.xpath('network_input/uri').text %> <% else %> <%= input.xpath('file_input/uri').text %> <% end %> </td>
    <td><%= link_to 'Show XML <i class="glyphicon glyphicon-zoom-in"></i>'.html_safe, change_attributes_wlabel_input_processings_path(live_event_id: @live_event_event_id, input_label: input.xpath('input_label').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
    <td><%= link_to 'Prepare <i class="glyphicon glyphicon-ok"></i>'.html_safe, prepare_wlabel_input_processings_path(live_event_id: @live_event_event_id, input_label: input.xpath('input_label').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
    <td><%= link_to 'Activate <i class="glyphicon glyphicon-film"></i>'.html_safe, activate_wlabel_input_processings_path(live_event_id: @live_event_event_id, input_label: input.xpath('input_label').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
    <td><%= link_to 'Delete <i class="glyphicon glyphicon-remove"></i>'.html_safe, delete_wlabel_input_processings_path(live_event_id: @live_event_event_id, input_label: input.xpath('input_label').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
  <% else %> 
    <tr class="item" id="item_<%= input.xpath('order').text %>">
    <td><%= input.xpath('order').text %></td><td><%= input.xpath('active').text %></td> <td><% if input.xpath('network_input/uri').text.length > 0 then %> <%= input.xpath('network_input/uri').text %> <% else %> <%= input.xpath('file_input/uri').text %> <% end %> </td>
    <td><%= link_to 'Show XML <i class="glyphicon glyphicon-zoom-in"></i>'.html_safe, change_attributes_wid_input_processings_path( live_event_id: @live_event_event_id, input_id: input.xpath('id').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %> </td>
    <td><%= link_to 'Prepare <i class="glyphicon glyphicon-ok"></i>'.html_safe, prepare_wid_input_processings_path( live_event_id: @live_event_event_id, input_id: input.xpath('id').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
    <td><%= link_to 'Activate <i class="glyphicon glyphicon-film"></i>'.html_safe, activate_wid_input_processings_path( live_event_id: @live_event_event_id, input_id: input.xpath('id').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
    <td><%= link_to 'Delete <i class="glyphicon glyphicon-remove"></i>'.html_safe, delete_wid_input_processings_path( live_event_id: @live_event_event_id, input_id: input.xpath('id').text ), { :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' }  %>  </td>
  <% end %>
  </tr>
<% end %>
  </tbody>
</table>


<br><br>



<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        Input label
      </th>
      <th>
        Loop source
      </th>
      <th>
        Uri
      </th>
      <th>
        Audio
      </th>
      <th>
        Video
      </th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    
    <% @inputs.each do |input| %>
      <tr>
        <td><%= input.input_label %></td>
        <td><%= input.loop_source %></td>
        <td><%= input.uri %></td>
        <td><%= link_to input.audio_selector.id, audio_selector_path(input.audio_selector), class: 'btn-sm btn-default' %></td>
        <td><%= link_to input.video_selector.id, video_selector_path(input.video_selector) , class: 'btn-sm btn-default' %></td>
        <td><input type="checkbox" id="<%= input.id %>" class="live_event_input" name="post[added] value="1" /> <%= link_to 'Add', single_add_wids_input_processings_path(id: input.id, event_id: input.live_event ), remote: true, class: 'btn-sm btn-default', data: {'input-id': input.id}  %> </td>
        <td><%= link_to 'Show', input_path(id: input.id, live_event_id: @live_event_event_id), class: 'btn-sm btn-default' %></td>
        <td><%= link_to 'Edit', edit_input_path(id: input.id, live_event_id: @live_event_event_id ), class: 'btn-sm btn-default' %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>


<%= link_to 'New Input', new_input_path(live_event_id: @live_event_event_id), class: 'btn-sm btn-success' %>

<button id="AddInputs" data-event-id="<%= @live_event_event_id %>" >Add inputs</button>

<button id="ReplacePlaylist" data-event-id="<%= @live_event_event_id %>" >Replace Playlist</button>

<br>
<br>
<br>
<br>
<br>
<br>
</div>
<div id="modal-window-prepare" class="modal fade"></div>
<div id="modal-window-activate" class="modal fade"></div>
<div id="modal-window-delete" class="modal fade"></div>
<div id="modal-window-single-add" class="modal fade"></div>
<div id="modal-window-change-attributes" class="modal fade"></div>

<div id="modal-window-add-inputs" class="modal fade"></div>
<div id="modal-window-replace-inputs" class="modal fade"></div>